# Generated by Django 4.2.13 on 2026-05-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_emissionrecord_parser_flags'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emissionrecord',
            new_name='ingestion_e_tenant__281016_idx',
            old_name='ingestion_e_tenant_i_status_idx',
        ),
        migrations.RenameIndex(
            model_name='emissionrecord',
            new_name='ingestion_e_tenant__87a790_idx',
            old_name='ingestion_e_tenant_i_scope_idx',
        ),
        migrations.RenameIndex(
            model_name='emissionrecord',
            new_name='ingestion_e_source__e3dd11_idx',
            old_name='ingestion_e_source__hash_idx',
        ),
        migrations.RenameIndex(
            model_name='emissionrecord',
            new_name='ingestion_e_activit_d0ada0_idx',
            old_name='ingestion_e_activity_date_idx',
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='parser_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
